apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gsel/app-argocddemo-config.git
    targetRevision: HEAD
    path: argocddemo
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocddemo
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
